version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: ":"
  Hello-World:
    machine: true
    steps:
      - run:
          name: Saying Hello
          command: |
            echo '文字出力成功'
workflows:
  Example-Workflow:
    jobs:
      - Hello-World