# CircleCIのバージョン
version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
          path: ~/webapp
      - run:
          command: corepack enable
          name: Package manager
      - run: yarn install --immutable
      - run:
          command: npm run build
          name: Build app