# CircleCIのバージョン
version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test

  Hello-World:
    machine: true # trueにすることで「circleci/classic:latest」適用
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'テストコードを追加してみた'
workflows:
  Example-Workflow:
    jobs:
      - build-and-test
      - Hello-World