# CircleCIのバージョン
version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    executor: win/server-2022
    working_directory: ~/repo
    # 処理内容
    steps:
      - checkout
      - run:
          name: Setting npm
          command: npm install
      - run:
          name: Run test
          command: npm run test
  Hello-World:
    machine: true
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'テストコードを追加してみた'
workflows:
  Example-Workflow:
    jobs:
      - build
      - Hello-World